language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: wy4Ipw2XGK9Af584eiWr3shkjcl0e86EtaBF7zaolwdtaeN1UXkNguY/A+TgFZewtaqRJ9+bPMW3KUimG0mJjeusndCOqNrE4Hs0oUi9Gy1goE2LQrsxiQD+kLnngQ3aaNJkE421yxZmVZBb1XLWIZHS9IhNfxkmuZe+VhMq5C8ruKaMaKipWMdtSXhoftN0UdZUbs/XOYbX51/6q8w86v03WdVHdP0mpOsOSZnq7C/6GvNPvwPjNu46M/lGih4oFl1t0sTm+782WR4tlr4nelUlDVpfo5dYKA0XNgoPr1OCE9wrkTXg4hY+sUrFO4Cskt59V0+A+cjlEgCMrKABGndlPVG5h7a15KsG+A8InnAEyYGOsptYyynLukdSCLeu7482BRtdw95GsokEwevHbNwuu/IavhS2VcyLp0OQQHCMvl0Yhw4YEtneYyw8e7q3l19vjMJGyALlzb0LAHVrsODe+S3654eYo9ZiY1TXIKbFLEDFWf7dCQuTaoIar0cCNAixHbIaqWyXRsFLQSVTbCsEbaJ/19waXFQhZzJ9wK6cB65qeojCl2xsrWI7aA6ucgVqDhqWIwYKqoBsGaDnKydNybJCq6UnJ3hzdp0Ve0SRpzUTai0OmPOX3zH5SRM7W5/mCb+L/414Shl31dPQQJIkjFExPmWXhzrmzU0TNsM=
  app: ancient-sea-13811
  on:
    repo: steffencrespo/car-purchase-decision
